name: Update SPDX licenses

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        # see https://github.com/actions/setup-java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          java-package: jdk
      - name: update
        run: tools/updateSpdx.sh
      - name: Archive Schema
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: schema
          path: schema/spdx.*
          if-no-files-found: error
  # TODO:
  # - if no changes: abort; else:
  # - detect version - pull from JSON `$comment`
  # - commit the changes
  #    - with message `bump SPDX licenses $version`
  #    - to branch 'spdx-licenses/$version'
  #    - signed as bot
  # - create pullresquest
